In [ ]:
#question1
import numpy as np
arr=np.array([1,2,3])
convert=arr.tolist()
print(convert)


[1, 2, 3]


In [ ]:
#question2
import numpy as np
m = np.arange(9).reshape(3,3)
print (m)
r=np.trace(m)
print(r)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
12


In [22]:
#question2 v.2
import numpy as np
m = np.arange(9).reshape(3,3)
r=0
for i in range (3):
  b=m[i,i]
  r=r+b
print(m)
print(r)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
12


In [4]:
#question3
import numpy as np

A=np.array([[1,2,3],[1,7,3]])
B=np.array([[8,69,45],[9,5,1]])
C=[]
for i in range (0,len(A)):
  a=A[i]
  
  for j in range (0,i+1):
    b=B[j]
    
  s=a+b
  C.append(s)
print(C)


[array([ 9, 71, 48]), array([10, 12,  4])]


numpy.ndarray

In [ ]:
#question4
import numpy as np
x=2
arr=np.array([[1,2],[3,5]])
l=arr.shape
for i in range (2):
  for j in range (0,2):
    b=arr[i,j]
    if b>x:
      print(b)



3
5


In [36]:
#question5
import numpy as np
from random import *
a = np.random.randint(3, 8,size=(10,5))
print(a)
b = a - a.mean(axis=1, keepdims=True)
print(b)

[[5 6 5 4 3]
 [6 7 3 3 7]
 [5 6 3 7 7]
 [3 7 4 4 5]
 [4 3 7 4 7]
 [5 4 6 4 4]
 [4 3 7 4 4]
 [4 6 5 4 6]
 [4 6 4 7 6]
 [3 5 3 3 7]]
[[ 0.4  1.4  0.4 -0.6 -1.6]
 [ 0.8  1.8 -2.2 -2.2  1.8]
 [-0.6  0.4 -2.6  1.4  1.4]
 [-1.6  2.4 -0.6 -0.6  0.4]
 [-1.  -2.   2.  -1.   2. ]
 [ 0.4 -0.6  1.4 -0.6 -0.6]
 [-0.4 -1.4  2.6 -0.4 -0.4]
 [-1.   1.   0.  -1.   1. ]
 [-1.4  0.6 -1.4  1.6  0.6]
 [-1.2  0.8 -1.2 -1.2  2.8]]
