In [3]:
import numpy as np
arr=np.array([1,2,3])
convert=arr.tolist()
print(convert)


[1, 2, 3]


In [7]:
import numpy as np
m = np.arange(9).reshape(3,3)
print (m)
r=np.trace(m)
print(r)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
12


In [37]:
import numpy as np

A=np.array([1,2,3])
B=np.array([8,69,45])
C=[]
for i in range (0,len(A)):
  a=A[i]
  
  for j in range (0,i+1):
    b=B[j]
    
  s=a+b
  l=C.append(s)
print(C)


[9, 71, 48]


In [79]:
import numpy as np
x=2
arr=np.array([[1,2],[3,5]])
l=arr.shape
for i in range (2):
  for j in range (0,2):
    b=arr[i,j]
    if b>x:
      print(b)



3
5


In [53]:
import numpy as np
from random import *
a=randint(1,10)
b=randint(1,10)
X = np.random.random((a,b))
m=X.mean(axis=1, keepdims=True)
print(m)

[[0.62183977]
 [0.41758642]
 [0.47188782]
 [0.49344167]]
